### ISSUE TITLE
Screenshots / Host urls

### ISSUE THREAD

**Issue by mike1000000000** [googlecodelabs/smarthome-local#11]
Screenshots and flow in the **Select the Smart Home App** section are not correct. 

The host URLs are not correct for 2 reasons: 

The output on mine is 'https://******.web.app' and the '<' signs are converted to html. 

`https://&lt;project-id&gt;.firebaseapp.com`

**Comment by proppy** [comment]
Are you referring to those pages ?
- https://codelabs.developers.google.com/codelabs/smarthome-local?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F#1
- https://codelabs.developers.google.com/codelabs/smarthome-local?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F#4

**Comment by proppy** [comment]
Closing as obsolete.
