### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by kempton1** [googlecodelabs/smarthome-local#12]
When I try to start the washer, it returns an error that the script start is missing.

npm start -- \ --deviceId=deviceid123 --projectId=automation-c2671 \ -- discoveryPortOut=3311 --discoveryPacket=HelloLocalHomeSDK
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kempton\AppData\Local\npm-cache\_logs\2020-11-13T08_44_15_680Z-debug.log

**Comment by proppy** [comment]
@kempton1 which version of node/npm are you using? The `npm start` command should be available (see https://docs.npmjs.com/cli/v6/commands/npm-start).

As a workaround you can use:
```
npm run start
```

**Comment by proppy** [comment]
Closing as obsolete.
