### ISSUE TITLE
On step 4, click 'Refresh' on web app does not working

### ISSUE THREAD

**Issue by king-ielec** [googlecodelabs/smarthome-local#17]
After I clicked the Refresh button on the web app, 
the console shows the log: "Request SYNC status:200",
but I can not see the 'Request SYNC for user 123' message on the firebase log.

My enviroment is:
Node.js version 14.18
Firebase-tools version 11.8.0

**Comment by king-ielec** [comment]
After I modified the code in public > main.js from 
fetch('/requestsync') to 
fetch('https://us-central1-my-project-id.cloudfunctions.net/requestsync')
then it work as expected, 
Is it a bug in coldelab example?

**Comment by raymondchlin** [comment]
This issue had been fixed.
