### ISSUE TITLE
No device found on chrome: // inspect page

### ISSUE THREAD

**Issue by youngda** [googlecodelabs/smarthome-local#3]
I'm distressed, follow the tutorial step by step.
Does Discover network targets need to be configured?
![微信截图_20200313002719](https://user-images.githubusercontent.com/12874231/76543635-c2546d00-64c1-11ea-87ed-a8d8e046bb5a.png)

**Comment by devunwired** [comment]
If your Home/Nest device does not show up in the inspect UI, it's likely either:
1. Your development machine and the Home device are not on the same local network
1. Your home device is not linked to the same Google account as your Actions console project
1. Your Actions console project does not have test mode enabled
