### ISSUE TITLE
Missing "On device testing"

### ISSUE THREAD

**Issue by webcodercompl** [googlecodelabs/smarthome-local#4]
I don't see "On device testing" in Test tab

![image](https://user-images.githubusercontent.com/63523191/79056990-74678c00-7c5c-11ea-8086-d021a326bf67.png)

I'm not sure if the issues are connected, but I don't see anything more than this in Chrome DevTools:

![image](https://user-images.githubusercontent.com/63523191/79057084-75e58400-7c5d-11ea-9057-b404d25dc395.png)

Starting a virtual device with a google assistant on phone works (the firebase database is also refreshed) but I can't start local execution

**Comment by devunwired** [comment]
Thanks for your feedback! The Actions console UI recently changed with the v1.0.0 SDK release last week, and we hadn't quite gotten the codelab instructions updated to match. The codelab has now been updated to reflect the new console.

To answer the specific question, the testing URL is now on the **Develop > Actions** page with the rest of the Local Home SDK configuration.

**Comment by webcodercompl** [comment]
Thanks for your answer! I noticed that "Enable local fulfillment for smart home Actions" codelabs has been updated. Unfortunately, there are still a few references to the old Actions console UI eg.

![image](https://user-images.githubusercontent.com/63523191/79120322-e3df9780-7d92-11ea-83b0-0fd7b642fe80.png)

The code in the repository uses the SDK version v0.2.0 - should something also be updated in the code due to the SDK update?

I'm trying to run the "app-done" version, unfortunately after I added testing URL in Develop > Actions I still don't see any local execution logs. (DevTools console looks as on my previous screen)

**Comment by devunwired** [comment]
Codelab should be up to date at this point. 

The fact that you are able to launch Chrome DevTools inspector on your device tells me that your  testing URL is being picked up correctly and it is running your local fulfillment app. If nothing else is happening, then your device is not triggering any `IDENTIFY` intents. This is most likely either because your scan configuration is incorrect/incomplete or the device you are looking to identify isn't present on the same network (or is unreachable).

**Comment by tobi-coder** [comment]
I have the same problem as @webcodercompl. I see only shell and SDK version. No identify intent. The devices are in the same network and reachable. Any other hints? Trying to get that working since hours.

**Comment by devunwired** [comment]
The virtual device will log a message each time a discovery payload is received. For the UDP broadcast in the codelab, this should happen roughly once every 60 seconds. If the virtual device is not seeing any traffic, then the scan configuration is likely incorrect or your device isn't properly linked to the same Google account as the test project.

**Comment by tobi-coder** [comment]
Thank you @devunwired. It was a stupid configuration mistake with the ports in the Action.
