### ISSUE TITLE
Unable to sync with service

### ISSUE THREAD

**Issue by mpahic** [googlecodelabs/smarthome-local#5]
Following the guide step by step, I get to the point where I have to link the service to home assistant. The service is correctly, shown [test] Smart home Actions, but when I click on it, it gets redirected, a busy circle and then nothing. 
The mentioned Stackdriver logs from the guide do not help, because no new logs are logged during this step.
As for the firebase functions, I have logs there only for the fakeauth function which I guess would redirect somewhere, but nothing happens (I did not paste the whole url log):
https://oauth-redirect.googleusercontent.com/r/localhatest?code=xxxxxx&state=AFVGnUE...
Function execution took 248 ms, finished with status code: 302

**Comment by Fleker** [comment]
Can you patch the authorization webhooks to match something like this: https://github.com/actions-on-google/smart-home-nodejs/commit/cfcc2156eb8e0bd85266ff71ca2c836dbea52601

The patch adds a manual step to approve account linking, which may add a necessary short delay to the linking process.

What phone are you using for the linking?

**Comment by mpahic** [comment]
Thank you, patching the code with manual login page worked.

By the way I am using Huawei P Smart.

Thank you for the support.

Regards,
Marko

sri, 15. tra 2020. u 18:11 Nick <notifications@github.com> napisao je:

**Comment by devunwired** [comment]
Merged this change into the codelabs.

Fixed with 8fdfece9950f8acb8c5c96a6da12f2e4d0311d51
