### ISSUE TITLE
Your project has used 100% of its monthly limit for Hosting GB transferred under your current plan. 

### ISSUE THREAD

**Issue by chadstick** [googlecodelabs/smarthome-local#7]
Am I supposed to be stopping communication with my virtual washer so I don't get charged "Hosting GB?" Please advise how I can do this and continue the code lab. Thx!

<img width="556" alt="hosting gb" src="https://user-images.githubusercontent.com/58739059/79588790-0b3baa80-809a-11ea-8af1-ba4177f07cf8.png">

.

**Comment by devunwired** [comment]
The files stored in Firebase Hosting for the codelab are the frontend UI components (HTML/CSS) taking up ~5-10KB of data. This data is only transferred when your browser loads the Hosting URL (it is not related to the requests made by the Assistant to the back end functions).

Transferring this much data would require you to refresh the page an immense number of times or have something else that is constantly querying your Hosting URL.

**Comment by chadstick** [comment]
OK thanks. I am personally not refreshing this page so it must be coming from somewhere else. I didn't see how I could drill down in the analytics nor do I know how to restrict access so I opened a ticket with Firebase support.

**Comment by devunwired** [comment]
We've been able to reproduce something similar internally. Currently investigating.

Can you confirm what stage you were at in the codelab when you noticed this? Had you completed and successfully tested the codelab? Or were you at one of the intermediate steps?

**Comment by chadstick** [comment]
Thanks for continuing to investigate. I was through step 5 when I began noticing this. I think I may be blocked from proceeding until this is resolved as it is prompting me to upgrade firebase plan which I obviously don't want to do at this point.

**Comment by chadstick** [comment]
I received a note back from FB support--all the requests seem to be coming from my router's IP address. If more details are helpful let me know.

**Comment by devunwired** [comment]
Could you also tell me which Home/Nest device(s) that were linked to your account for testing? For example: Nest Hub, Google Home speaker, etc.?

**Comment by chadstick** [comment]
I have 2 Google Homes, 1 Nest Hub, 1 or 2 minis, Nest wi-fi (3 pts), and a TV w/ Google Assistant.

**Comment by devunwired** [comment]
Are all of these devices linked to the Google Account you were using for your Actions console project?

**Comment by chadstick** [comment]
Yes

**Comment by proppy** [comment]
Closing as obsolete.
