### ISSUE TITLE
Unable to debug with chrome:inspect

### ISSUE THREAD

**Issue by chadstick** [googlecodelabs/smarthome-local#8]
I see my devices using chrome:inspect and I am able to successfully issue commands to GA devices, but I can't see any devices in my console and get the error pictured below.

![image](https://user-images.githubusercontent.com/58739059/80818412-bbc8a480-8b98-11ea-9c12-ad3b60e42090.png)

**Comment by devunwired** [comment]
Please clarify at which step of the codelab you are seeing this error. Also, please clarify what you mean by "devices" in each of the instances above. Home/Nest device? Virtual device?

**Comment by chadstick** [comment]
I encountered this at step 8: "Debug the Typescript App." I meant that I could see my Google Home show up on the chrome:inspect team and it recognizes the "start washer" command, but I am unable to see my virtual washer and its device id in the console.

**Comment by devunwired** [comment]
From the codelab steps:
> You should see a list of devices on the page and your app URL should appear under the name of your Google Home device.

You indicated that you can see your Home device listed, but is your app URL also visible there with a blue "inspect" link? Is this how you entered the console when you saw that error?

Successfully sending commands means your cloud fulfillment is properly connected, but if you do not see the local app URL showing up in `chrome://inspect` then there is an issue loading the local fulfillment code.

**Comment by chadstick** [comment]
Now I am unable to see my Home device listed via chrome://inspect. In the instructions it advises:

Important: If the URL does not appear, then unlink and relink the Actions on Google project, and then reboot your Google Home device. It can take up to 20 minutes for your settings in the Actions console to take effect.

How/where can I accomplish the unlink and relink step referenced above?

**Comment by devunwired** [comment]
> Now I am unable to see my Home device listed via chrome://inspect.

If the Home device is not visible at all, this is not an issue with your project. Verify the devices are on the same local network. In some cases you may need to reboot Chrome on your development machine.

> How/where can I accomplish the unlink and relink step referenced above?

You should only attempt this if you can see the Home device, but not the local app inspect link below it. This is the same process as described in the **Link to Google Assistant** section as part of [Step 3](https://codelabs.developers.google.com/codelabs/smarthome-local/index.html#2). To unlink, you'll see your **[test]** app listed under **Linked services** instead.

Note that the 20 minutes referenced in the description is only the time it can take the first time you save your testing URL in the console to propagate to the devices.

**Comment by proppy** [comment]
Closing as obsolete.
