### ISSUE TITLE
Home Device does not send IDENTIFY to app

### ISSUE THREAD

**Issue by ibnharoon** [googlecodelabs/smarthome-local#9]
When I click the "inspect" button on the device list (step 8), I did not see the IDENTIFY intent printed on the chrome console.
I don't see any traffic from the home device to the app on port 3311, 3312 or 3388.

Is this the correct URL:
> https://<project-id>.firebaseapp.com/local-home/index.html
Why is it pointing to external URL, instead of localhost?

**Comment by devunwired** [comment]
> Is this the correct URL:
> ...
> Why is it pointing to external URL, instead of localhost?

Step 6 of the codelab deploys the local fulfillment app to Firebase Hosting, so the testing URL in the console should be `https://<project-id>.firebaseapp.com/local-home/index.html`

> When I click the "inspect" button on the device list (step 8), I did not see the IDENTIFY intent printed on the chrome console. I don't see any traffic from the home device to the app on port 3311, 3312 or 3388.

The best place to start debugging is with your scan configuration. Make sure the values match those used to launch the virtual device in Step 7. The virtual device will log a message each time a discovery packet is received, so you should be able to determine if the device scanning is working correctly.

If that is successful, the `IDENTIFY` intent should appear to your local fulfillment app with the payload response.

**Comment by ibnharoon** [comment]
![image](https://user-images.githubusercontent.com/517816/85799144-99b05600-b6f3-11ea-92c3-1216a93373eb.png)
I only see this when I click inspect. I can issue command on my home device and see the state change on the smart home remote firebase app (https://<project-id>.firebaseapp.com/), but I still don't see any IDENTIFY specific traffic on the local network. The port settings is correct on both the smart home action and the local app.

**Comment by ibnharoon** [comment]
![image](https://user-images.githubusercontent.com/517816/85800609-222ff600-b6f6-11ea-81a9-65107916faaa.png)

Now I can see the UDP traffic on 3311 but no IDENTIFY intent printed on the browser console.

**Comment by ibnharoon** [comment]
It's working now. Unlink and link and re-booting the home device did it.
